### PR TITLE
Add withHandleToHANDLE from ansi-terminal

### LINKED ISSUE #51: Allow conversion from Handle -> HANDLE
In writing cross-platform Haskell, I have a Handle but need to convert it to a HANDLE for use with System.Win32.File.

There is a private implementation [in ansi-terminal](http://hdiff.luite.com/cgit/ansi-terminal/tree/System/Console/ANSI/Windows/Foreign.hs#n302).

### PR DESCRIPTION
**Pull request by RyanGlScott**
This brings over the [`withHandleToHANDLE`](https://github.com/feuerbach/ansi-terminal/blob/a93e6f5941104b52395b9f82a4556836461878ba/System/Console/ANSI/Windows/Foreign.hs#L337-L360) function from the `ansi-terminal` library. I also added a basic test to ensure that it works with the standard handles.

I contemplated implementing the opposite direction (`hANDLEToHandle`?), but I'm not quite sure what the best way to do it would be. There's at least two different implementations ([this](http://git.haskell.org/ghc.git/blob/6c869f906b879bc746ea1aa3e79e02f146d85093:/iserv/src/GHCi/Utils.hsc#l17) and [this](http://git.haskell.org/ghc.git/blob/6c869f906b879bc746ea1aa3e79e02f146d85093:/compiler/ghci/GHCi.hsc#l538)) in GHC, for instance. As a result, I decided to leave that part alone.

Fixes #51.

### CODE REVIEW

**Comment by Mistuke** [comment]
Thanks @RyanGlScott ! W.r.t the inverse function, they're both essentially the same. I wrote the one in [GHCi.hsc](http://git.haskell.org/ghc.git/blob/6c869f906b879bc746ea1aa3e79e02f146d85093:/compiler/ghci/GHCi.hsc#l538) but don't know where the second came from. But they both do the same. so the one in `Utils.hsc` is a bit more general. We can probably include that one.

**Comment by RyanGlScott** [comment]
Hrm. I tried implementing `hANDLEToHandle` like so:

```diff
diff --git a/System/Win32/Types.hsc b/System/Win32/Types.hsc
index 4393c51..1e5e447 100755
--- a/System/Win32/Types.hsc
+++ b/System/Win32/Types.hsc
@@ -32,12 +32,13 @@ import Data.Word (Word8, Word16, Word32, Word64)
 import Foreign.C.Error (Errno(..), errnoToIOError)
 import Foreign.C.String (newCWString, withCWStringLen)
 import Foreign.C.String (peekCWString, peekCWStringLen, withCWString)
-import Foreign.C.Types (CChar, CUChar, CWchar, CInt(..), CIntPtr, CUIntPtr)
+import Foreign.C.Types (CChar, CUChar, CWchar, CInt(..), CIntPtr(..), CUIntPtr)
 import Foreign.ForeignPtr (ForeignPtr, newForeignPtr, newForeignPtr_)
-import Foreign.Ptr (FunPtr, Ptr, nullPtr)
+import Foreign.Ptr (FunPtr, Ptr, nullPtr, ptrToIntPtr)
 import Foreign.StablePtr (StablePtr, freeStablePtr, newStablePtr)
 import Foreign (allocaArray)
 import GHC.IO.FD (FD(..))
+import GHC.IO.Handle.FD (fdToHandle)
 import GHC.IO.Handle.Types (Handle(..), Handle__(..))
 import Numeric (showHex)
 import System.IO.Error (ioeSetErrorString)
@@ -56,6 +57,7 @@ finiteBitSize :: (Bits a) => a -> Int
 finiteBitSize = bitSize
 #endif

+#include <fcntl.h>
 #include <windows.h>
 ##include "windows_cconv.h"

@@ -218,6 +220,13 @@ nullFinalHANDLE = unsafePerformIO (newForeignPtr_ nullPtr)
 iNVALID_HANDLE_VALUE :: HANDLE
 iNVALID_HANDLE_VALUE = castUINTPtrToPtr (-1)

+foreign import ccall "_open_osfhandle"
+  _open_osfhandle :: CIntPtr -> CInt -> IO CInt
+
+hANDLEToHandle :: HANDLE -> IO Handle
+hANDLEToHandle handle =
+  _open_osfhandle (fromIntegral (ptrToIntPtr handle)) (#const _O_BINARY) >>= fdToHandle
+
 foreign import ccall unsafe "_get_osfhandle"
   c_get_osfhandle :: CInt -> IO HANDLE
```

It works, but only in a limited sense. You can, for instance, print to standard output:

```
> import System.Win32.Types
> import Graphics.Win32
> import System.IO
> __stdout <- getStdHandle sTD_OUTPUT_HANDLE
> stdout2 <- hANDLEToHandle __stdout
> hPutStrLn stdout2 "foo"
foo
```

However, `stdout2` is _not_ the same thing as the `stdout` `Handle`:

```
> stdout == stdout2
False
> stdout
{handle: <stdout>}
> stdout2
{handle: <file descriptor: 3>}
```

`stdout` is a `FileHandle`, but `stdout2` is a `DuplexHandle`.

Is this acceptable?

**Comment by Mistuke** [comment]
To be perfectly honest, I'm not even sure that `handle -> fd`, `fd -> handle` returns the same. It's likely it's internally duplicating the Handle. But also the way GHC handles Handles is complex. I'm perfectly willing to accept that function with that caveat. If it causes problems for anyone I'll look into it then. We can just add a note to the documentation.

**Comment by RyanGlScott** [comment]
OK, I've added `hANDLEToHandle` with a little disclaimer.

**Comment by Mistuke** [comment]
Many thanks kind sir!

**Pull request merged**
