### PR TITLE
Add getConsoleScreenBufferInfo

### PR DESCRIPTION
**Pull request by tswelsh**
## Description
Adds a foreign import of `GetConsoleScreenBufferInfo` and the functions `getConsoleScreenBufferInfo` and `getCurrentConsoleScreenBufferInfo`.  The former is a translation of the API call, the latter is probably what people will need most in practice.

## Motivation and Context
Required to calculate terminal size mainly, e.g. `stack` has an open issue for getting terminal size on Windows, `ghcid` needs to know about it etc.  There is an existing package `terminal-size` but I think that it makes sense to add it to this central place, plus this gives access to the whole `CONSOLE_SCREEN_BUFFER_INFO` if anybody should need it.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [x] I have not added a new Haskell dependency.
- [x] I have included a changelog entry.
- [x] I have not modified the version of the package in `Win32.cabal`.

### CODE REVIEW

**Comment by Mistuke** [comment]
Hi @tswelsh,

Thanks for the pull request. The build's failed because I'm still maintaining compatibility with GHC's as old as `7.8` since this is a low level binding.

```
[03:57:02] Console.hsc: In function 'main':
[03:57:02] Console.hsc:105:5: warning: implicit declaration of function 'hsc_alignment'
[03:57:02] Console.hsc:105:20: error: expected expression before 'CONSOLE_SCREEN_BUFFER_INFO'
[03:57:02] Console.hsc:127:20: error: expected expression before 'COORD'
[03:57:02] Console.hsc:145:20: error: expected expression before 'SMALL_RECT'
[03:57:02] compiling dist\build\System\Win32\Console_hsc_make.c failed (exit code 1)
[03:57:02] command was: E:\GHC\i386\ghc-7.8.4\mingw\bin\gcc.exe -c dist\build\System\Win32\Console_hsc_make.c -o dist\build\System\Win32\Console_hsc_make.o -U__i686 -fno-stack-protector -D__GLASGOW_HASKELL__=708 -Dmingw32_BUILD_OS=1 -Di386_BUILD_ARCH=1 -Dmingw32_HOST_OS=1 -Di386_HOST_ARCH=1 -Iinclude -fno-strict-aliasing -Wall -Idist\build\autogen -include dist\build\autogen\cabal_macros.h -IE:\GHC\i386\ghc-7.8.4\lib\bytestring-0.10.4.0\include -IE:\GHC\i386\ghc-7.8.4\lib\base-4.7.0.2\include -IE:\GHC\i386\ghc-7.8.4\lib\integer-gmp-0.5.1.0\include -IE:\GHC\i386\ghc-7.8.4\lib/include -IE:\GHC\i386\ghc-7.8.4/lib/include/
[03:57:02] Process exited with code 1
```

The problem is that these structs don't exist in `Windows.h` for these types sometimes in the 32 bit version of the toolchain because they used to be [different from](https://ghc.haskell.org/trac/ghc/ticket/10726) the 64 bit ones.

The way we work around this problem now is to provide internal compatibility shims, such as this https://github.com/haskell/win32/blob/master/include/winternl_compat.h

Could you make a similar one for the types above? They should be in `Wincon.h` so a `wincon_compat.h` is needed.

**Comment by vincenthz** [comment]
looking forward to see that supported in `Win32`; we also have a bindings for getConsoleScreenBufferInfo in https://github.com/haskell-foundation/foundation/blob/master/basement/Basement/Terminal/Size.hsc but as I mentioned to the author, it would make sense to have this centrally in `Win32`.

**Comment by tswelsh** [comment]
I have pushed a commit which follows the existing *_compat.h modules.  I haven't been able to test this locally with older GHCs - I tried with stack but failed (due to a GHC bug on Windows I think?), and haven't got round to trying with just cabal.  I won't have time to work on this for a little while so thought I'd push what I had - hope it passes the checks.

**Comment by Mistuke** [comment]
Hmmm It seems 7.8.4 does provide the types.. but hsc2hs didn't like something before. I'll take a look once I'm back near a computer next week.

**Comment by tswelsh** [comment]
Pushed another commit, it passes all the checks!  My original mistake was not including alignment.h - that is the compatibility bit needed for older GHCs.

**Comment by Mistuke** [comment]
Indeed, thanks!

**Pull request merged**
