### PR TITLE
Fix foreign import calling convention on SetWindowLongPtrW. Appears that...

### PR DESCRIPTION
**Pull request by Kludgy**
... this should be WINDOWS_CCONV.

### CODE REVIEW

**Comment by ndmitchell** [comment]
As per discussions with CLC, I agreed to weigh in when I thought patches looked good or bad. This one looks good. The patch that switched from stdcall to capi was f065e76290149350f20eda0a24fc45f6ee0e2088, which seems to have been trying to improve it for Win64, but given @Kludgy has actually tried it, and this fix looks better anyway, I think the previous fix was probably always buggy.

I'm curious why the Win32 package uses `WINDOWS_CCONV` and not `WINAPI` for its calling convention symbol, since `WINAPI` is the preprocessor symbol the `windows.h` header uses, so it would "match" the docs much better.

**Comment by Kludgy** [comment]
I'm not sure what @igfoo's intent was, but renaming `WINDOWS_CCONV` to
`WINAPI` could lead to some unfortunate bugs due to collisions with the
version in `Windows.h`.

**Comment by ndmitchell** [comment]
True. I guess HSWINAPI would not clash and keep the connection obvious.

**Comment by ndmitchell** [comment]
This seems to have lead to a bug on 32bit: https://ghc.haskell.org/trac/ghc/ticket/10165

**Comment by Kludgy** [comment]
This means that SetWindowLongPtrW will have to be declared with capi
instead of ccall for mingw32 specifically.

I don't know why this is an exception to the rule, but it is easy enough to
accommodate. I'll push a new commit to test asap.

**Comment by ndmitchell** [comment]
Yes, I don't understand why it's an exception to the rule - it seems we may have discovered that information previously and then lost it.

**Comment by m37** [comment]
I don't believe this issue is caused by the calling convention, rather that `SetWindowLongPtrW` is not available on 32-bit *at all*.  On 32-bit, one must use `SetWindowLongW` instead.

MSDN documentation for [SetWindowLongPtr](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633591%28v=vs.85%29.aspx).

**Comment by Kludgy** [comment]
But the Windows.h include at the top of Window.hsc should already provide a
macro that expands accordingly.

**Comment by Kludgy** [comment]
I see. Of course this won't expand as a string. Good catch!

Was this ever working? :)

**Comment by m37** [comment]
Probably not :/

**Comment by m37** [comment]
@Kludgy,

I would still use WINDOWS_CCONV as you did, otherwise it looks like there is something special going on wrt. the calling convention (which there isn't).

**Comment by Kludgy** [comment]
While not a PR yet, I can't test right now, but here's a candidate in case anyone can review/test in the meantime:

https://github.com/Kludgy/win32/commit/9e52103b8b4a9bfb486e2289257ec61ac682eb89

**Pull request merged**
