### PR TITLE
Add CSIDL_LOCAL_APPDATA

### PR DESCRIPTION
**Pull request by pmlodawski**
Hello! Is there a possibility to add CSIDL_LOCAL_APPDATA? It is useful when getting this folder on Windows.

### CODE REVIEW

**Comment by mpkh** [comment]
Why this pull request is not merged yet?

**Comment by Heather** [comment]
Why it's not merged so far?

**Comment by ndmitchell** [comment]
Seems fine. My only concern is there are a lot of these shell variables, and rather than add them one by one, wouldn't it be better to add them all at once? Specifically probably all from https://msdn.microsoft.com/en-gb/library/windows/desktop/bb762494(v=vs.85).aspx, perhaps up to Version 5.0 (which seems to be the existing limit, allowing Win2k/WinME, but not Win98, see https://msdn.microsoft.com/en-gb/library/windows/desktop/bb776779(v=vs.85).aspx).

**Comment by thoughtpolice** [comment]
Merged (via df9393c978c1d56c803ee06f457e047b90a76a67 etc)

**Pull request closed without merging**
