### PR TITLE
Add export lists to all modules

### LINKED ISSUE #174: Exports are too unconstrained
Currently many of `Win32`'s modules have no export list, meaning that they often unintentionally export what were supposed to be internal functions (e.g. FFI imports). For instance, see `System.Win32.Event`, which exports `c_WaitForSingleObject` and many others. This ends up breaking `haskeline`.

As a rule in a library like this all modules should have an export list.

### PR DESCRIPTION
**Pull request by bgamari**
## Description
This prevents the foreign C bindings from being exposed to clients.

## Motivation and Context
Previously the internal `c_*` bindings leaked from many modules. Fixes #174.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have not added a new Haskell dependency.
- [ ] I have included a changelog entry.
- [ ] I have not modified the version of the package in `Win32.cabal`.

### CODE REVIEW

**Comment by bgamari** [comment]
To-do:
 * [ ] verify that no exports were unintentionally dropped
 * [ ] fix trailing whitespace

**Comment by bgamari** [comment]
It turns out that `System.Directory.Internals.Windows.setTimes` currently uses `System.Win32.Time.c_SetFileTime`. It looks like it does so because the type of `setFileTime` is actually incorrect. It is currently:
```haskell
setFileTime :: HANDLE -> FILETIME -> FILETIME -> FILETIME -> IO ()
```

whereas conceptually it should be:

```haskell
setFileTime :: HANDLE -> Maybe FILETIME -> Maybe FILETIME -> Maybe FILETIME -> IO ()
```

Strictly speaking, Win32's `SetFileTime` [allows](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfiletime) the `Nothing` case to be encoded as either a `NULL` pointer or as a pointer to a 0 value, so technically `System.Win32.Time.setFileTime` current interface can be used by passing `0` arguments. However, I do wonder whether we shouldn't just change the type while we doing a major bump.

**Comment by Mistuke** [comment]
> It turns out that `System.Directory.Internals.Windows.setTimes` currently uses `System.Win32.Time.c_SetFileTime`. It looks like it does so because the type of `setFileTime` is actually incorrect. It is currently:
> 
> ```haskell
> setFileTime :: HANDLE -> FILETIME -> FILETIME -> FILETIME -> IO ()
> ```
> 
> whereas conceptually it should be:
> 
> ```haskell
> setFileTime :: HANDLE -> Maybe FILETIME -> Maybe FILETIME -> Maybe FILETIME -> IO ()
> ```
> 
> Strictly speaking, Win32's `SetFileTime` [allows](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfiletime) the `Nothing` case to be encoded as either a `NULL` pointer or as a pointer to a 0 value, so technically `System.Win32.Time.setFileTime` current interface can be used by passing `0` arguments. However, I do wonder whether we shouldn't just change the type while we doing a major bump.

I'm all for it. We did this before in 2.6.0.0 with #83 but I guesswe missed one.

**Comment by Mistuke** [comment]
> It turns out that `System.Directory.Internals.Windows.setTimes` currently uses `System.Win32.Time.c_SetFileTime`. It looks like it does so because the type of `setFileTime` is actually incorrect. It is currently:
> 
> ```haskell
> setFileTime :: HANDLE -> FILETIME -> FILETIME -> FILETIME -> IO ()
> ```
> 
> whereas conceptually it should be:
> 
> ```haskell
> setFileTime :: HANDLE -> Maybe FILETIME -> Maybe FILETIME -> Maybe FILETIME -> IO ()
> ```
> 
> Strictly speaking, Win32's `SetFileTime` [allows](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfiletime) the `Nothing` case to be encoded as either a `NULL` pointer or as a pointer to a 0 value, so technically `System.Win32.Time.setFileTime` current interface can be used by passing `0` arguments. However, I do wonder whether we shouldn't just change the type while we doing a major bump.

I'm all for it. We did this before in 2.6.0.0 with #83 but I guesswe missed one.

**Comment by wz1000** [comment]
@Mistuke can we backport this to the `2.10.1` branch for GHC 9.0.2?

**Comment by wz1000** [comment]
Alternatively, we could backport https://github.com/haskell/win32/commit/530c5ec7d98edf77f2605afed8449f62f45ae93b to `2.10.0.1`

**Comment by Mistuke** [comment]
> Alternatively, we could backport [530c5ec](https://github.com/haskell/win32/commit/530c5ec7d98edf77f2605afed8449f62f45ae93b) to `2.10.0.1`

If this solves it I rather backport this. This PR changes the public interface so I don't think I can backport it with a revision release.

**Comment by wz1000** [comment]
I've bumped Win32 on 9.0.2 to `2.12.0.1`, which includes this as well as 530c5ec . All it needed was a hackage revision to `Cabal-3.4.1.0` on hackage, which has been made.

You don't need to backport anything now. Thanks for the help!

**Pull request merged**
